AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Minimalist TODO Application Main SAM Stack

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
    Description: Environment name passed to nested applications

Resources:
  FrontendApp:
    Type: AWS::Serverless::Application
    Properties:
      # Local path to your packaged nested template
      Location: domains/frontend/frontend.yaml
      Parameters:
        Environment: !Ref Environment

  # AuthenticationApp:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: domains/authentication/authentication.yaml
  #     Parameters:
  #       Environment: !Ref Environment

  # ApiApp:
  #   Type: AWS::Serverless::Application
  #   DependsOn: AuthenticationApp
  #   Properties:
  #     Location: domains/api/api-gateway.yaml
  #     Parameters:
  #       # Pull the state machine ARN from the authentication nested app’s Outputs
  #       RegisterStateMachineArn: !GetAtt AuthenticationApp.Outputs.RegisterStateMachineArn

Outputs:
  Environment:
    Description: Deployment environment
    Value: !Ref Environment

  FrontendURL:
    Description: URL of the static website
    Value: !GetAtt FrontendApp.Outputs.FrontendURL

  # HttpApiUrl:
  #   Description: Base URL for the HTTP API
  #   Value: !GetAtt ApiApp.Outputs.HttpApiUrl

  FrontendBucketName:
    Description: S3 bucket for static website files
    Value: !GetAtt FrontendApp.Outputs.FrontendBucketName
